databases:
  - name: dailyblockchaindb
    plan: free
    databaseName: dailyblockchaindb
    user: dailyblockchaindb_user

services:
  - type: web
    plan: free
    name: TheDailyBlockchainMainRepo
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn nxt.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dailyblockchaindb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
