# Generated by Django 5.0.2 on 2024-08-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('rsi', models.TextField()),
                ('ma', models.TextField()),
                ('cp', models.TextField()),
                ('pm', models.TextField()),
                ('srl', models.TextField()),
                ('va', models.TextField()),
                ('rsi_image_url', models.URLField(max_length=255)),
                ('ma_image_url', models.URLField(max_length=255)),
                ('cp_image_url', models.URLField(max_length=255)),
                ('pm_image_url', models.URLField(max_length=255)),
                ('srl_image_url', models.URLField(max_length=255)),
                ('va_image_url', models.URLField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generate_tracker', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dailytechnical',
            },
        ),
    ]
