# Generated by Django 5.0.1 on 2024-02-08 03:00

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_profile_first_name_remove_profile_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_post',
            field=tinymce.models.HTMLField(),
        ),
    ]
