# Generated by Django 5.0.2 on 2024-03-02 04:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_post',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='images'),
        ),
    ]
