# Generated by Django 5.0.2 on 2024-03-27 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cryptodetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptodetail',
            old_name='name',
            new_name='title',
        ),
    ]
