# Generated by Django 5.0.2 on 2024-03-27 09:22

import autoslug.fields
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_name_cryptodetail_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptodetail',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.CreateModel(
            name='CryptoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('description', tinymce.models.HTMLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_post', to='api.profile')),
            ],
        ),
    ]
