# Generated by Django 5.0.2 on 2024-03-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_cryptopost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptopost',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
