# Generated by Django 5.0.2 on 2024-03-27 09:36

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_cryptopost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptopost',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title'),
        ),
    ]
